version: '3.8'
services:
  app:
    working_dir: /var/www/html
  node:
    working_dir: /var/www/html
networks:
  appnet:
    driver: bridge
volumes:
  cachedata:
    driver: local
  dbdata:
    driver: local
