version: '3.8'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: myshippingdocker/app:latest
    networks:
     - appnet
    volumes:
     - .:/var/www/html
  cache:
    image: redis:alpine
    networks:
     - appnet
    volumes:
     - cachedata:/data
  db:
    image: mysql:5.7
    networks:
     - appnet
    volumes:
     - dbdata:/var/lib/mysql
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: myshippingdocker/node:latest
    networks:
     - appnet
    volumes:
     - .:/var/www/html
